# Generated by Django 5.1.7 on 2026-07-14 09:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.CharField(max_length=500)),
                ('pickup_location', models.CharField(max_length=500)),
                ('dropoff_location', models.CharField(max_length=500)),
                ('current_cycle_used_hours', models.FloatField()),
                ('trip_start_datetime', models.DateTimeField()),
                ('total_distance_miles', models.FloatField(default=0.0)),
                ('total_drive_hours', models.FloatField(default=0.0)),
                ('total_duty_hours', models.FloatField(default=0.0)),
                ('num_days', models.IntegerField(default=1)),
                ('cycle_hours_remaining', models.FloatField(default=0.0)),
                ('restarts_required', models.IntegerField(default=0)),
                ('route_geometry', models.JSONField(blank=True, default=dict)),
                ('route_stops', models.JSONField(blank=True, default=list)),
                ('daily_logs_data', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
